services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092" # External port for Kafka
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://kafka:29092 # Internal and external listeners
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9092 # Advertised listeners for internal and external clients
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT # Map security protocols to listener names
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT # Inter-broker communication uses the PLAINTEXT listener
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Zookeeper connection string
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network

networks:
  kafka-network: